version: ""

services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db

  api:
    build: .
    ports:
      - 3000:3001
    environment:
      PORT: 3001
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: todo-api
      NAME: Saransh Sahu

    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
